name: AB Scout

on:
  workflow_dispatch:

jobs:
  scraper:

    runs-on:
      - self-hosted
      - backup
      - playwright

    env:
      HEADLESS: "true"
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Runner
        run: |
          echo "Runner OS: ${{ runner.os }}"

      ##################################################
      # Linux (NAS)
      ##################################################

      - name: Build Docker Image (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo docker build -t ab-scout .

      - name: Run AB Scout (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo docker run --rm \
            -e HEADLESS \
            -e TELEGRAM_BOT_TOKEN \
            -e TELEGRAM_CHAT_ID \
            ab-scout

      ##################################################
      # Windows (Laptop)
      ##################################################

      - name: Build Docker Image (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          docker build -t ab-scout .

      - name: Run AB Scout (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          docker run --rm `
            -e HEADLESS `
            -e TELEGRAM_BOT_TOKEN `
            -e TELEGRAM_CHAT_ID `
            ab-scout