name: AB Scout

on:
  workflow_dispatch:

jobs:
  scraper:
    runs-on:
      - self-hosted
      - nas
      - arm64
      - playwright

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          sudo docker build -t ab-scout .

      - name: Run AB Scout
        run: |
          sudo docker run --rm \
            -e HEADLESS=true \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            ab-scout